/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package horserace;

import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.concurrent.TimeUnit;

import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JPanel;

public class App {
    public String getGreeting() {
        return "Hello World!"+System.getProperty("user.dir");
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
				JFrame f = new JFrame("hi");
				HorseManager hm = new HorseManager("horses.txt");
				// Horse horse = new Horse('a', "asdf", 0.1);
				// Horse horse = hm.addHorse('a', "asdf", 0.1);
				// Horse horse2 = hm.addHorse('b', "asd2", 1);
				// Horse horse2 = new Horse('b', "asd2", 1);
				// try{
				// 	horse.setImage("images/horses/donner.png");
				// 	horse.setSaddle("images/saddles/saddle.png");
				// 	horse2.setImage("images/horses/tescomealdeal.png");
				// 	horse2.setSaddle("images/saddles/greensaddle.png");
				// }
				// catch(Exception e) {
				// 	System.exit(1);
				// }
				RaceManager rm = new RaceManager("races.txt");
				hm.getHorses().forEach((k,v) -> {
					rm.addHorse(v, k);
				});
				// race.addHorse(horse, 1);
				// race.addHorse(horse2, 2);
				f.add(rm.getRace().getLanesUI());
				f.pack();
				f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				f.setResizable(false);
				f.setVisible(true);
				for(int i=0;i<1;i++) {
				try{
				TimeUnit.SECONDS.sleep(1);
				} catch(Exception e) {};
				rm.startRace();
				
			}

    }
}
