/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package horserace;

import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.concurrent.TimeUnit;

import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JPanel;

public class App {
    public String getGreeting() {
        return "Hello World!"+System.getProperty("user.dir");
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
				JFrame f = new JFrame("Click lane to change horse and color, start race also restarts race!");
				// race.addHorse(horse, 1);
				// race.addHorse(horse2, 2);
				f.add(new RaceChooser("horses.txt", "races.txt"));
				f.pack();
				f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				f.setResizable(false);
				f.setVisible(true);
				for(int i=0;i<1;i++) {
				try{
				TimeUnit.SECONDS.sleep(1);
				} catch(Exception e) {};
				
			}

    }
}
